### ISSUE TITLE
Como surgiu a ideia do cc @sseraphini?

### ISSUE THREAD

**Issue by pjonatansr** [sibelius/ama#2]

**Comment by sibelius** [comment]
It was a way to scale my DM (direct messages) and mentoring

A lot of people asked the same questions/advices over and over again, so I've asked them to ask in a public tweet and tag me

Over time I figure it out I don't need to answer all questions

I gave opportunity for other people to answer the questions

**Comment by RFS-Junior** [comment]
Is there any bot to help you on Twitter?

**Comment by pjonatansr** [comment]
@R-ronivaldo, eu falei sobre isso nesse artigo:

https://dev.to/pjonatansr/como-a-comunidade-brasileira-utiliza-o-twitter-para-aprender-em-publico-345b

Spoiler: É manual o esforço dos likes e rts do Sibelius.

**Comment by sibelius** [comment]
it is better to open a new issue for a new question

this is the long term idea https://github.com/sibelius/ccsseraphini/issues/224
