### ISSUE TITLE
Como incentivar pessoas não dev a codar/interagir com código?

### ISSUE THREAD

**Issue by jeffque** [sibelius/ama#4]
Time não técnico está se sentindo inseguro para acompanhar os devs codando, eles dizem que não tem "conhecimento o suficiente".

Como incentivar eles a participar do mob programming e que eles pratiquem learn on demand?

**Comment by sibelius** [comment]
Non-Technical people won't be able to code or evaluate the quality of the code.

But they can validate the Product. Add continuous integration and continuous deployment to be easy to test new code in main branch (staging), and generate a code preview for each pull request in the frontend
