### ISSUE TITLE
Como é feito o acompanhamento de um estagiário(a) na Entria?

### ISSUE THREAD

**Issue by italosantana** [sibelius/ama#5]
Acabou de entrar um novo estagiário(a)...

Fala mais um pouco sobre o code review, tasks são mais 'tranquilas' do que os demais estão há mais tempo trabalhando, pair programing, e afins...

**Comment by sibelius** [comment]
The new developer will read all our written documentation using docusaurus.
They will set up projects in the machine, only reading the documentation.
They need to open issues of parts of the documentation is not clear enough or outdated
We gonna create an issue tracking (a queue of issues) that they need to solve, the issues start easy and will getting harder as they progress.
We provide pair programming to show the structure of the monorepo/code, and also when the developer is stuck somehow.
The issues will make the developer learn concepts as they progress, and get more context.
They also have access to customer support chat to understand the customer problems
They have access to sentry (error monitoring) to see how many errors and which errors we have in production
They will also improve their own issues and tests other developers issues/tasks
Reviewing every team member pull requests will let them get more context faster
