### ISSUE TITLE
How to improve at context switching?

### ISSUE THREAD

**Issue by fersilva16** [sibelius/ama#6]
You always say that you're really good at context switching, and I've always wondered how can you do that because I always suffer trying it.

Would you say it's your skill? There's some way to practice that?

**Comment by sibelius** [comment]
You can model each context as a process in a operational system

You need to optimize your job scheduling to make it efficient.

You need to save and restore the context of each job when moving from one context to another

You can keep the context written down in some texts notes to help at first, then you just keep them in your memory

The more you switch the better you get, at first you are gonna be unproductive, but it will get better over time
