### ISSUE TITLE
Do you think you’re in control of your life 100% of the time?

### ISSUE THREAD

**Issue by jgcmarins** [sibelius/ama#7]
Could you explain your thoughts about being in control of your life?

**Comment by sibelius** [comment]
I'm not 100% control of my life, and that's ok.

I'm focusing my strategic to be Antifragile (Antifragile: Things That Gain from Disorder, taleb book).

How am I getting more antifragile?

I'm acquiring a lot of knowledge from different sources. I'm getting theory knowledge from books, articles and newsletters. Furthermore, I'm getting practical knowledge building my startup, communities and audience. This knowledge let me make the best decision when a bad event happen.
I'm also increasing my social capital, generating more value for a lot of people. I generate value for my startup, making it more productivity. I generate value for developers, providing mentorship and great content. I generate value for beginners to lending my social capital for them using cc @sseraphini. I generate value for VCs to generate qualified leads to them.

In the worst case scenario, I would work for some Silicon Valley Startup, earning more than I earn right now.
