### ISSUE TITLE
CC @sseraphini [o podcast] - #1

### ISSUE THREAD

**Issue by lucasfcosta** [sibelius/ama#8]
# O quê?

Dia 7 de Julho, 15:30, vamos gravar o primeiro CC @sseraphini.

Durante mais ou menos uma hora, o oráculo @sibelius e eu vamos responder no Discord as perguntas melhores perguntas enviadas pela comunidade.

A live vai ser editada e chega num feed como podcast também :)

# Mande sua pergunta 👇

A pergunta pode ir nessa issue, ou via Twitter, basta marcar o “cc @sseraphini”.

Caso você tenha gostado muito de uma pergunta de outra pessoa, dê um like, um reaction, ou um reply pra gente saber. Perguntas que sejam muito populares têm mais chances de serem respondidas.

**Comment by sibelius** [comment]
working https://podcasts.google.com/feed/aHR0cHM6Ly9jYy1zc2VyYXBoaW5pLmNhc3Rvcy5jb20vZmVlZA?sa=X&ved=0CAMQ4aUDahcKEwjomLLa57D6AhUAAAAAHQAAAAAQAQ&hl=en-BR
