### ISSUE TITLE
How to be more consistent? How to be more disciplined?

### ISSUE THREAD

**Issue by noghartt** [sibelius/ama#9]
- How to be more consistent doing anything in your life?
- How to be more disciplined?

**Comment by sibelius** [comment]
## How to be more consistent doing anything in your life?

To be consistent, you should not stop doing something.
One way to motivate you to not stop doing something, is to keep a `streak` count.
My Duolingo streak is 826 days. So I won't miss a dueling class any day to avoid breaking it.
The biggest the streak count, the strong the motivation to keep doing it.
Another approach for consistency is to go against yourself. You should do something even if you don't wanna, even if you are tired, just do it.

![image](https://user-images.githubusercontent.com/2005841/192166116-eac80c3e-e22e-4c85-bbd0-eb98d2ce9956.png)

## How to be more disciplined?

Discipline is to do what you need to do.
Every time you notice that you are not doing what you should be doing, you go back to what you need to do, even if you don't like it.
Discipline is applying the same rules for you and for everybody else.

## What do discipline and consistency have in common?

They only work when you don't open exceptions.
You should not open exceptions for yourself.
